# https://pre-commit.com
default_install_hook_types: [commit-msg, pre-commit]
default_stages: [pre-commit, manual]
fail_fast: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb', '800']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: ['--unsafe']
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        types: [python]
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: no-commit-to-branch
      - id: trailing-whitespace
        types: [python]
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: cz check
        args: [--commit-msg-file]
        require_serial: true
        language: system
        stages: [commit-msg]
      - id: absolufy-imports
        name: absolufy-imports
        entry: absolufy-imports
        require_serial: true
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff
        args: ["--fixable=ERA001,F401,F841,T201,T203,I001"]
        require_serial: true
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        require_serial: true
        language: system
        types: [python]
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        args: [--check-sourced]
        language: system
        types: [shell]
      - id: poetry-check
        name: poetry check
        entry: poetry check
        language: system
        files: pyproject.toml
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9003
    hooks: 
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: lintr
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: no-debug-statement
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks: 
      - id: check-added-large-files
        args: ['--maxkb=200']
      - id: end-of-file-fixer
        exclude: '\.Rd'
  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
    # Only required when https://pre-commit.ci is used for config validation
    - id: check-pre-commit-ci-config
  - repo: local
    hooks:
    - id: forbid-to-commit
      name: Don't commit common R artifacts
      entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
      language: fail
      files: '\.(Rhistory|RData|Rds|rds)$'
      # `exclude: <regex>` to allow committing specific files
